spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-parking
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.gonemesis.org/realms/parkingSI
          jwk-set-uri: https://keycloak.gonemesis.org/realms/parkingSI/protocol/openid-connect/certs
cors:
  origin:
    url: http://localhost:4200
keycloak:
  username: username
  password: password
  url: https://keycloak.gonemesis.org
stripe:
  public-key: key
  secret-key: key
  webhook-secret: key
