spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart-parking
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:3000/realms/smart-parking
          jwk-set-uri: http://localhost:3000/realms/smart-parking/protocol/openid-connect/certs
