version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--http-port=3000"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: always

  app_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: smart-parking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - app_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  keycloak_data:
  app_data: