version: '3.7'

services:
  app_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: smart-parking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - app_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  app_data:
